name: medallion-architecture-starter
schedule: daily
start_date: "2024-01-01"

# This is a starter pipeline demonstrating the medallion architecture pattern
# with Bronze (raw), Silver (cleaned), and Gold (aggregated) layers

default_connections:
  google_cloud_platform: my-bigquery-connection
  snowflake: my-snowflake-connection

notifications:
  slack:
    - channel: data-pipelines
      success: false  # Only notify on failures
